// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fs, port;

  express = require("express");

  fs = require("fs");

  app = new express();

  app.use("/img", express["static"](__dirname + "/img"));

  app.use(express.bodyParser());

  app.get("/event/:id?", function(req, res) {
    var id;
    id = req.params.id || req.query.id;
    return fs.readFile('./json/ALL.json', 'utf-8', function(err, data) {
      var event, events, invalid, _i, _len;
      events = JSON.parse(data);
      invalid = true;
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        event = events[_i];
        if (event.id === id) {
          invalid = false;
          res.send(event);
          break;
        }
      }
      if (invalid) {
        return res.send({
          error: "event not found with id " + id
        });
      }
    });
  });

  app.get("/event_img/:id", function(req, res) {
    return res.sendfile(__dirname + ("/img/" + req.params.id + ".jpg"));
  });

  port = process.env.PORT || 80;

  app.listen(port, function() {
    return console.log("listening on port " + port);
  });

}).call(this);
