// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fs;

  express = require("express");

  fs = require("fs");

  app = new express();

  app.use("/img", express["static"](__dirname + "/img"));

  app.use(express.bodyParser());

  app.get("/event/:id?", function(req, res) {
    var id;
    id = req.params.id || req.query.id;
    return fs.readFile('./json/ALL.json', 'utf-8', function(err, data) {
      var event, events, valid, _i, _len;
      events = JSON.parse(data);
      valid = false;
      for (_i = 0, _len = events.length; _i < _len; _i++) {
        event = events[_i];
        if (event.id === id) {
          res.send(event);
          break;
        }
      }
      if (!valid) {
        return res.send({
          error: "event not found with id " + id
        });
      }
    });
  });

  app.listen(80);

}).call(this);
